rm -rf cardano-sl
rm -rf daedalus
rm -rf react-polymorph
rm -rf mantis
rm -rf iohk-ops
rm -rf cardanodocs.com
rm -rf plutus-prototype
rm -rf stack2nix
rm -rf TreasuryCoin
rm -rf ouroboros-spec
rm -rf scrypto
rm -rf plato
rm -rf cardano-crypto
rm -rf plato_dockerfiles
rm -rf mantis-daedalus
rm -rf nixops
rm -rf iodb
rm -rf nixpkgs
rm -rf scdsl
rm -rf cardano-report-server
rm -rf slips
rm -rf haskoin
rm -rf sbt-verify
rm -rf cardano-sl-style-guides
rm -rf cardano-sl-explorer
rm -rf ekg-statsd
rm -rf dns
rm -rf genesis-auditor
rm -rf leveldb
rm -rf dns-resolver-windows
rm -rf Scorex
rm -rf cbor-sets-spec
rm -rf ekg-statsd-example
rm -rf parity
rm -rf purescript-base58
rm -rf purescript-websocket-simple
rm -rf pvss-haskell
rm -rf SalesApp
rm -rf cardano-docs.iohk.io
rm -rf qeditas
rm -rf purescript-node-http
rm -rf hydra
rm -rf block_expectation_paper
rm -rf meteor-line
rm -rf accounts-line
rm -rf purescript-test-task
rm -rf ecip-quorum
rm -rf line-oauth
rm -rf line-js-api
rm -rf rscoin-haskell
rm -rf rscoin-core
rm -rf network-transport-tcp
rm -rf network-transport
rm -rf cardano-updater
rm -rf cardano-docs
rm -rf scrypto-benchmarks
rm -rf auth-avl
rm -rf purescript-pux-socketio-example
rm -rf scorex-etc
rm -rf rscoin-be-language-pack
rm -rf iodb-whitepaper
rm -rf time-warp-nt
rm -rf time-warp
rm -rf elm-export
rm -rf qeditas.org
rm -rf qeditas-cryptohash
rm -rf qeditas-ledgertheory
rm -rf qeditas-egal
rm -rf qeditas-theory
rm -rf rscoin-nixops
rm -rf ChimpHttpCallTester
rm -rf scorex-docs
rm -rf Lagonaki
rm -rf Permacoin-consensus

rm tezos
